### PR TITLE
Swap "Get Started" for YouTube

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I wasn't too sure which one to remove but I went with Get started as the same sort of info is above in black banner - what are your thoughts?

**Comment by brockfanning** [comment]
Hi Lucy, that would be fine with me. I'm wondering though if we should link to a playlist within the CODE channel, so that it doesn't have the non-Open SDG videos. Should I check with CODE about that?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I see that the playlists have been created. Should we use this? https://youtube.com/playlist?list=PLN9TixRVC43SxqfqTZRzWzsQ1jWnXuGkI

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning that makes sense - I've just made change so think we can merge, right?

**Comment by brockfanning** [comment]
Sounds good!

**Pull request merged**
